feat: :sparkles: Converted javascript to typescript
KiveshVirasamy/flight-tracker- pull request #1
Opened 2023-02-26 10:08 UTC by KiveshVirasamy

Changed the following files to typescript: main.js, dom-manipulation.js, leaflet-services.js. I also removed used files

2023-02-26 10:20 UTC, CharelMarais requested changes
Look good just double check there are no Implicite any's you can view my comments.

2023-02-26 10:20 UTC, CharelMarais commented on src/dom-manipulation.ts
> +type Flight = [
I would say you need to move your type of declaration to a separate

2023-02-26 10:20 UTC, CharelMarais commented on src/dom-manipulation.ts
>    const speed = Utils.convertMPSToKPH(flight[11] ?? 0.0);
Just make sure your variables have set types and not any.

2023-02-26 10:20 UTC, CharelMarais commented on src/tsconfig.json
> +  "compilerOptions": {
You should add "noImplicitAny": true to check for any Implicite Any's

2023-02-26 10:22 UTC, KiveshVirasamy commented on src/dom-manipulation.ts
> +type Flight = [
Okay will do for the separation of concerns?

2023-02-26 10:23 UTC, KiveshVirasamy commented on src/dom-manipulation.ts
>    const speed = Utils.convertMPSToKPH(flight[11] ?? 0.0);
I totally overlooked that one on it now.

2023-02-26 10:23 UTC, KiveshVirasamy commented on src/tsconfig.json
> +  "compilerOptions": {
Okay adding now. Thanks man.

2023-02-26 11:10 UTC, merged

2023-03-25 11:02 UTC, theadley commented
Most of these are unresolved, yet merged anyway. There are still type errors and you have loads of explicit and implicit `any` types all over the show. Why merge?