Observables
KiveshVirasamy/flight-tracker- pull request #3
Opened 2023-02-26 10:16 UTC by KiveshVirasamy

Please check if my observable is okay

2023-02-26 15:27 UTC, CharelMarais reviewed
Looks good, I made one comment that you can review.

2023-02-26 15:27 UTC, CharelMarais commented on src/main.ts
> +  flightData$.subscribe((flightData) => {
You can combine 2 observables using `concatMap()` to get the output for the list of flights and then subscribe to that one observable on both `36` and `49`.

2023-02-26 17:12 UTC, KiveshVirasamy commented on src/main.ts
> +  flightData$.subscribe((flightData) => {
Okay cool thanks man

2023-03-05 10:05 UTC, KiveshVirasamy commented on src/main.ts
> +  flightData$.subscribe((flightData) => {
I added the concat map

2023-03-05 10:16 UTC, MihlaliMgwebi requested changes
Can approve after change.

2023-03-05 10:16 UTC, MihlaliMgwebi commented on src/main.ts
> +    flightData.states.forEach((flight: any) => {
Specifiy the type. Any is frowned upon.

2023-03-05 10:16 UTC, MihlaliMgwebi commented on src/utils/utilities.ts
> +@param {number} deg - The degree angle.
Great comments

2023-03-05 10:16 UTC, KiveshVirasamy commented on src/main.ts
> +    flightData.states.forEach((flight: any) => {
okay on it

2023-03-05 10:17 UTC, KiveshVirasamy commented on src/utils/utilities.ts
> +@param {number} deg - The degree angle.
Thanks

2023-03-05 11:04 UTC, MihlaliMgwebi approved these changes

2023-03-05 12:46 UTC, merged